name: Deploy to EC2

on:
  push:
    branches: [ "main" ]  # main 브랜치에 push 될 때 작동

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Check jar exists
        run: ls -al target

      - name: Copy jar to EC2 with scp
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$EC2_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem target/ec2-hello-0.0.1-SNAPSHOT.jar $EC2_USER@$EC2_HOST:/home/ec2-user/app/
          
      - name: Run app on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            pkill -f 'java -jar' || true
            nohup java -jar ~/app/target/ec2-hello-0.0.1-SNAPSHOT.jar > ~/app/nohup.out 2>&1 &
